// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/article": {
            "get": {
                "description": "Get list of all articles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article"
                ],
                "summary": "Get all articles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/article.Article"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new article with file upload",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article"
                ],
                "summary": "Create new article",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Article Title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Article Short Summary",
                        "name": "short_summary",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Article Full Text",
                        "name": "full_text",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Article Author",
                        "name": "author",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Cover Image",
                        "name": "cover_image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Article Reading Time",
                        "name": "reading_time",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/article/{id}": {
            "get": {
                "description": "Get a article by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article"
                ],
                "summary": "Get article by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Article ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/article.Article"
                        }
                    }
                }
            },
            "put": {
                "description": "Update article details by ID (with optional new files)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article"
                ],
                "summary": "Update article",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Article ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Article Title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Article Short Summary",
                        "name": "short_summary",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Article Full Text",
                        "name": "full_text",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Article Author",
                        "name": "author",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Cover Image",
                        "name": "cover_image",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Article Reading Time",
                        "name": "reading_time",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updated",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a article by ID",
                "tags": [
                    "article"
                ],
                "summary": "Delete article",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Article ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/freebook": {
            "get": {
                "description": "Get list of all freebooks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "freebook"
                ],
                "summary": "Get all freebooks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/freebook.FreeBook"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new freebook with file upload",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "freebook"
                ],
                "summary": "Create new freebook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Book Title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Book Summary",
                        "name": "summary",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Book Author",
                        "name": "author",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Book Pages",
                        "name": "pages",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Cover Image",
                        "name": "cover_image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "PDF File",
                        "name": "pdf_file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/freebook/{id}": {
            "get": {
                "description": "Get a freebook by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "freebook"
                ],
                "summary": "Get freebook by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/freebook.FreeBook"
                        }
                    }
                }
            },
            "put": {
                "description": "Update freebook details by ID (with optional new files)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "freebook"
                ],
                "summary": "Update freebook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Book Title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Book Summary",
                        "name": "summary",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Book Author",
                        "name": "author",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Book Pages",
                        "name": "pages",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Cover Image",
                        "name": "cover_image",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "PDF File",
                        "name": "pdf_file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updated",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a freebook by ID",
                "tags": [
                    "freebook"
                ],
                "summary": "Delete freebook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/paidbook": {
            "get": {
                "description": "Get list of all paidbooks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paidbook"
                ],
                "summary": "Get all paidbooks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/paidbook.PaidBook"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new paidbook with file upload",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paidbook"
                ],
                "summary": "Create new paidbook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Book Title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Book Summary",
                        "name": "summary",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Book Author",
                        "name": "author",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Book Pages",
                        "name": "pages",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Book Price",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Cover Image",
                        "name": "cover_image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "PDF File",
                        "name": "pdf_file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/paidbook/{id}": {
            "get": {
                "description": "Get a paidbook by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paidbook"
                ],
                "summary": "Get paidbook by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/paidbook.PaidBook"
                        }
                    }
                }
            },
            "put": {
                "description": "Update paidbook details by ID (with optional new files)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paidbook"
                ],
                "summary": "Update paidbook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Book Title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Book Summary",
                        "name": "summary",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Book Author",
                        "name": "author",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Book Pages",
                        "name": "pages",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Book Price",
                        "name": "price",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Cover Image",
                        "name": "cover_image",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "PDF File",
                        "name": "pdf_file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updated",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a paidbook by ID",
                "tags": [
                    "paidbook"
                ],
                "summary": "Delete paidbook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "article.Article": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "cover_image": {
                    "type": "string"
                },
                "full_text": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reading_time": {
                    "type": "integer"
                },
                "short_summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "freebook.FreeBook": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "cover_image": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "pdf_file": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "paidbook.PaidBook": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "cover_image": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "pdf_file": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Online Library API",
	Description:      "This is a Online Library API with CRUD operations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
