basePath: /
definitions:
  domain.FreeBook:
    properties:
      author:
        type: string
      cover_image:
        type: string
      id:
        type: integer
      pages:
        type: integer
      pdf_file:
        type: string
      summary:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a Online Library API with CRUD operations.
  title: Online Library API
  version: "1.0"
paths:
  /books:
    get:
      description: Get list of all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.FreeBook'
            type: array
      summary: Get all books
      tags:
      - books
    post:
      consumes:
      - application/json
      description: Add a new Book
      parameters:
      - description: Book data
        in: body
        name: Book
        required: true
        schema:
          $ref: '#/definitions/domain.FreeBook'
      produces:
      - application/json
      responses:
        "201":
          description: created
          schema:
            type: string
      summary: Create new Book
      tags:
      - books
  /books/{id}:
    delete:
      description: Delete a Book by ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: deleted
          schema:
            type: string
      summary: Delete Book
      tags:
      - books
    get:
      description: Get a Book by its ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.FreeBook'
      summary: Get Book by ID
      tags:
      - books
    put:
      consumes:
      - application/json
      description: Update Book details by ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated Book
        in: body
        name: Book
        required: true
        schema:
          $ref: '#/definitions/domain.FreeBook'
      produces:
      - application/json
      responses:
        "200":
          description: updated
          schema:
            type: string
      summary: Update Book
      tags:
      - books
swagger: "2.0"
